# Site
name: "CHuyên sinh"
title: "chuyensinh"
description: "Biology is life."
meta_description: "Chia sẻ kiến thức, tài liệu ôn thi HSG môn sinh học."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'honguyenvantan@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: ''

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/'
    
# Other
markdown: kramdown
highlighter: rouge
